# Application Configuration File
app:
  environment: "${ENVIRONMENT:development}"

# Spring Configuration
spring:
  application:
    name: Vanguard-Ops

  # Database Configuration
  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true

# JWT Config
jwt:
  secret: "${JWT_SECRET}"
  expires-in-ms: "${JWT_EXPIRES_IN}"
  issuer: "${JWT_ISSUER}"

# Server Configuration
server:
  port: 8080

# Swagger Configuration
springdoc:
  swagger-ui:
    path: /api-docs.html